spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:shotdo}?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:yourpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

aws:
  s3:
    bucket: shotdo-auth-photos-yeojisun
    region: ap-northeast-2
  credentials:
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
